import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillGoogleCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/siddhi.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import cloud from "../public/cloud.png";
import web from "../public/webb.png";
import dsa from "../public/dsa.png";
import harvestify from "../public/Harvestify.png";
import nft from "../public/nft.png";
import room from "../public/room3d.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Siddhi Patel Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-sans text-xl">DEVELOPEDBYSID</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-purple-500 text- to-blue-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="../public/Siddhi Patel _Resume.pdf"
                  download
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-purple-600 font-medium dark:text-purple-400 md:text-6xl">
              Siddhi Patel
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Cloud Developer and UI/UX Designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer whose interests lie in Cloud Computing, UI/UX, and 3D
              designing. I am a diligent individual who is committed to
              advancing my professional capabilities and personal development. I
              find joy in acquiring new knowledge and actively engaging in team
              collaborations.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://www.linkedin.com/in/siddhi-patel12/"
                target="_blank"
              >
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/siddhiipatell" target="_blank">
                <AiFillGithub />
              </a>
              <AiFillGoogleCircle />
            </div>
            <div className="mx-auto bg-gradient-to-b from-purple-500 to-blue-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 pt-10 dark:text-white ">
              Software Skills
            </h3>
            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I possess like to present a diverse range of skills that I possess, including the following:
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p> */}
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={cloud} width={100} height={100} />
              <h3 className="text-2xl font-medium pt-8 pb-2  ">
                Cloud Developer
              </h3>
              <p className="py-1">
                As a cloud developer, I have acquired a comprehensive skill set
                that enables me to design, develop, and deploy applications and
                services on cloud platforms.
              </p>
              <h4 className="py-2 text-purple-600">Cloud Platforms</h4>
              <p className="text-gray-800 ">Amazon Web Services (AWS)</p>
              <p className="text-gray-800 ">Microsoft Azure</p>
              <p className="text-gray-800 ">Google Cloud Platform (GCP)</p>
              <p className="text-gray-800 "></p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-2xl font-medium pt-10 pb-2 ">
                UI/UX Designer & 3D Artist
              </h3>
              <p className="py-1">
                I bring a unique blend of creativity, technical skills, and a
                deep understanding of user-centric design principles.
              </p>
              <h4 className="py-2 text-purple-600">Design Tools I Use</h4>
              <p className="text-gray-800 ">Illustrator</p>
              <p className="text-gray-800 ">Photoshop</p>
              <p className="text-gray-800 ">Figma</p>
              <p className="text-gray-800 ">Blender</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={web} width={100} height={100} />
              <h3 className="text-2xl font-medium pt-14 pb-2 ">
                Web Developer
              </h3>
              <p className="py-1">
                I possess a robust skill set that enables me to design and
                develop dynamic and interactive web applications.
              </p>
              <h4 className="py-2 text-purple-600">Technical Stack</h4>
              <p className="text-gray-800 ">React.js</p>
              <p className="text-gray-800 ">Node.js</p>
              <p className="text-gray-800 ">MongoDB</p>
              <p className="text-gray-800 ">HTML, CSS, JS</p>
            </div>
          </div>
        </section>

        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={dsa}
              />
              <p className="text-center italic text-sm dark:text-white">
                It is a website which acts a visualizer tool for easy
                understanding of data structures and algorithms deployed on
                cloud.
              </p>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={harvestify}
              />
              <p className="text-center italic text-sm dark:text-white">
                Harvestify is a ML crop recommendation model which recommends
                crops, fertilizers and predict diseases based on the inputs
                provided.
              </p>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={nft}
              />
              <p className="text-center italic text-sm dark:text-white" >
                A python-based automation script used to automate the task of
                creating NFTs using different layers.
              </p>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={room}
              />
              <p className="text-center italic text-sm dark:text-white">
                This is a blender based 3d isometric room model.
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
